# Generated by Django 4.2.1 on 2024-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_with_to_a_stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(default=None, max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default=None, max_length=100, verbose_name='Отчество')),
                ('created_request', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки запроса на связь')),
                ('phone_number_client', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('contact_by_phone_number', models.BooleanField(default=False, verbose_name='Связь по номеру телефона')),
                ('contact_by_telegram', models.BooleanField(default=False, verbose_name='Связь по telegram')),
                ('contact_by_vk', models.BooleanField(default=False, verbose_name='Связь по VK')),
                ('contact_by_whatsApp', models.BooleanField(default=False, verbose_name='Связь по whatsApp')),
                ('client_request', models.CharField(default='Просто разобрать свой гардероб', max_length=100, verbose_name='Запрос клиента')),
            ],
            options={
                'verbose_name': 'Запрос на связь со  стилистом',
                'verbose_name_plural': 'Запросы',
                'db_table': 'Contact_with_to_a_stylist',
            },
        ),
    ]
