# Generated by Django 4.2.1 on 2024-08-09 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_clothers_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название образа')),
            ],
            options={
                'verbose_name': 'Категория одежды',
                'verbose_name_plural': 'Категории одежды',
                'db_table': 'Categorys_clothers_users',
            },
        ),
        migrations.CreateModel(
            name='Clothers_users_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cloth_images_users', verbose_name='изображение одежды')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='your_hanger.category_clothers_users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Одежда пользователей',
                'verbose_name_plural': 'Одежда пользователей',
                'db_table': 'Clothers_users_load',
            },
        ),
    ]
