# Generated by Django 4.2.1 on 2024-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion_post_news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id новости(публикации)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок новости')),
                ('title_text', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='текст/содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_news_images', verbose_name='изображение')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления новости в базу')),
            ],
            options={
                'verbose_name': 'Новостные посты о модных тенденциях',
                'verbose_name_plural': 'Новости мира моды',
                'db_table': 'Fashion_post_news',
            },
        ),
    ]
