# Generated by Django 4.2.1 on 2024-08-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_people_clothers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, null=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'Категория ообраза',
                'verbose_name_plural': 'Категории образов',
                'db_table': 'Categorys_people_clothers',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, null=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'Ж/М',
                'verbose_name_plural': 'Категории людей (женщины и мужчины)',
                'db_table': 'People_categorys',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название образа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cloth_images', verbose_name='изображение образа')),
                ('slug', models.CharField(max_length=100, null=True, verbose_name='слаг')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_fashon.category_people_clothers', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Oбраз',
                'verbose_name_plural': 'Образы',
                'db_table': 'Sample_people_clothers',
            },
        ),
        migrations.AddField(
            model_name='category_people_clothers',
            name='people_women_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_fashon.people', verbose_name='мужчина/женщина'),
        ),
    ]
